// Generated by Selenium IDE
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import dev.failsafe.internal.util.Assert;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import org.openqa.selenium.edge.EdgeDriver;

import static org.junit.Assert.*;
import static org.assertj.core.api.Assertions.assertThat;

import io.github.bonigarcia.seljup.SeleniumJupiter;
import io.github.bonigarcia.wdm.WebDriverManager;


@ExtendWith(SeleniumJupiter.class)
public class SeleniumTest {

  private WebDriver driver;

  private Map<String, Object> vars;

  JavascriptExecutor js;

  @BeforeEach
  public void setUp() {
    driver = new EdgeDriver();
  }
  
  @Test
  void testVanillaBasicLogin() {
    driver.get(
            "https://bonigarcia.dev/selenium-webdriver-java/login-form.html");

    driver.findElement(By.id("username")).sendKeys("user");   
    driver.findElement(By.id("password")).sendKeys("user"); 
    driver.findElement(By.cssSelector("button")).click(); 

    assertThat(driver.findElement(By.id("success")).isDisplayed()).isTrue(); 
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }
}
